name: "License Check"
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
    paths:
      - package.json

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0" # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: gem install license_finder
      - uses: actions/checkout@v3
      - run: license_finder
      - run: echo $(pwd)
